accounts/urls.py
from django.urls import path
from .views import user_register

app_name='accounts'
urlpatterns = [
    path('signup/',user_register,name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('reserve/',include('reserve.urls')),
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

reserve/urls.py
from django.urls import path
from .views import reservefood

app_name='reserve'
urlpatterns = [
    path('',reservefood,name='reserve'),
]

webs/urls.py
from django.urls import path
from .views import show,PostDetail

urlpatterns = [
    path('',show,name='home'),
    path('<int:pk>/',PostDetail.as_view(),name='detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

reserve/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
class ReserveModel(models.Model):
    name=models.CharField(_('نام و نام خانوادگی'),max_length=150)
    email=models.EmailField(_('ایمیل'),default='abc@gmail.com')
    phone=models.CharField(_('تلفن'),max_length=15)
    guests=models.PositiveIntegerField(_('تعداد مهمان ها'))
    date=models.DateField(_('تاریخ'),auto_now=False,auto_now_add=False,default='2023-01-01')
    time=models.TimeField(_('ساعت'),auto_now=False,auto_now_add=False,default='08:00')
    def __str__(self):
        return self.name

webs/models.py
from django.db import models
from django.utils.translation import gettext as _ # import farsi

# Create your models here.
#name,desc,price,preptime,created,img,food-type

class Food(models.Model):
    TYPES=[
        ('iranifood','غذای ایرانی'),
        ('fastfood','فست فود'),
        ('juices','نوشیدنی')
    ]

    name=models.CharField(_('نام غذا'),max_length=100)
    describtion=models.CharField(_('توضیحات'),max_length=50)
    price=models.PositiveIntegerField(_('قیمت'))
    preptime=models.PositiveSmallIntegerField(_('مدت آماده سازی'),default=2)
    created=models.DateTimeField(_('تاریخ انتشار'),auto_now_add=True)
    image=models.ImageField(_('تصویر'),upload_to='webs/')
    type=models.CharField(_('نوع غذا'),max_length=20,choices=TYPES,default='fastfood')

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms


#user-email-pass-passconfirm
class RegisterForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password_confirm=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

reserve/forms.py
from django import forms
from .models import ReserveModel

class ReserveForm(forms.ModelForm):
    class Meta:
        model=ReserveModel
        fields='__all__'

accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect

# Create your views here.

def user_register(request):
    template='registration/signup.html'
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request,template,{
                    'form':form,
                    'error_message':'این نام کاربری از قبل موجود است'

                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request,template,{
                    'form':form,
                    'error_message':'این ایمیل از قبل موجود است'

                })
            elif form.cleaned_data['password']!=form.cleaned_data['password_confirm']:
                return render(request,template,{
                    'form':form,
                    'error_message':'پسوردها همخوانی ندارند'
                })
            else:
                user=User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user.save()
                return HttpResponseRedirect('login')
    
    
    else:
        form=RegisterForm()
    
    return render(request,template,{'form':form})

reserve/views.py
from django.shortcuts import render,redirect
from .forms import ReserveForm
# Create your views here.
def reservefood(request):
    form=ReserveForm()
    if request.method=='POST':
        form=ReserveForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form=ReserveForm()
    return render(request,'reserve/reserve.html',{'form':form})

webs/views.py
from django.shortcuts import render
from .models import Food
from django.views import generic

# Create your views here.
def show(request):
    posts=Food.objects.all()
    return render(request,'webs/index.html',{'posts':posts})

class PostDetail(generic.DetailView):
    model=Food
    template_name='webs/detail.html'
    context_object_name='posts'

reserve/templates/reserve/reserve.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block title %}RESERVE{% endblock title %}

{% block navbar %}
</ul>
<a class="navbar-brand m-auto" href="#">
<img src="assets/imgs/logo.svg" class="brand-img" alt="">
<span class="brand-txt">کافه غذا</span>
</a>
<ul class="navbar-nav">
{% endblock navbar %}

{% block context %}
<br><br><br><br><br><br>
<div class='container'>
<form method='POST' style="color:white;text-align:right;">
{% csrf_token %}
<h2>فرم رزرو</h2>
<hr><br>
{{form|crispy}}
<br>
<button class="btn btn-primary ml-xl-4" type='submit' style="color:white;font-size:20 ">رزرو میز</button>
<br>
</form>
<br>





{% endblock context %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Start your development with FoodHut landing page.">
        <meta name="author" content="Devcrud">
        <title>{% block title %}{% endblock title %}</title>
<!-- font icons -->
<link rel="stylesheet" href="{% static 'assets/vendors/themify-icons/css/themify-icons.css' %}">

<link rel="stylesheet" href="{% static 'assets/vendors/animate/animate.css' %}">

<!-- Bootstrap + FoodHut main styles -->
<link rel="stylesheet" href="{% static 'assets/css/foodhut.css' %}">
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home" style="direction:rtl;">
    
    <!-- Navbar -->
    <nav class="custom-navbar navbar navbar-expand-lg navbar-dark fixed-top" data-spy="affix" data-offset-top="10">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">خانه</a>
                </li>
                {% block navbar %}
                
                {% endblock navbar %}
                <li class="nav-item">
                {% if user.is_authenticated %}
                    <a href='{% url 'logout' %}' class="btn btn-primary ml-xl-4">خروج از {{user.username}}</a>
                {% else %}
                    <a href='{% url 'login' %}' class="btn btn-primary ml-xl-4">ورود یا ثبت نام</a>
                {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    <!-- header -->
    {% block header %}{% endblock header %}
    {% block context %}{% endblock context %}
    
    <!-- page footer  -->
    <div class="container-fluid bg-dark text-light has-height-md middle-items border-top text-center wow fadeIn">
        <div class="row">
            <div class="col-sm-4">
                <h3>EMAIL US</h3>
                <P class="text-muted">info@website.com</P>
            </div>
            <div class="col-sm-4">
                <h3>CALL US</h3>
                <P class="text-muted">(123) 456-7890</P>
            </div>
            <div class="col-sm-4">
                <h3>FIND US</h3>
                <P class="text-muted">12345 Fake ST NoWhere AB Country</P>
            </div>
        </div>
    </div>
    <div class="bg-dark text-light text-center border-top wow fadeIn">
        <p class="mb-0 py-3 text-muted small">&copy; Copyright <script>document.write(new Date().getFullYear())</script> Made with <i class="ti-heart text-danger"></i> By <a href="#">Babak Bayat</a></p>
    </div>
    <!-- end of page footer -->

	<!-- core  -->
    <script src="{% static 'assets/vendors/jquery/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'assets/vendors/bootstrap/bootstrap.bundle.js' %}"></script>

    <!-- bootstrap affix -->
    <script src="{% static 'assets/vendors/bootstrap/bootstrap.affix.js' %}"></script>

    <!-- wow.js -->
    <script src="{% static 'assets/vendors/wow/wow.js' %}"></script>
    
    <!-- google maps -->
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtme10pzgKSPeJVJrG1O3tjR6lk98o4w8&callback=initMap"></script>

    <!-- FoodHut js -->
    <script src="{% static 'assets/js/foodhut.js' %}"></script>
</body>
</html>

templates/header.html
<header id="home" class="header">
    <div class="overlay text-white text-center">
        <h1 class="display-2 font-weight-bold my-3" style="color:red;">کافه غذا</h1>
        <h2 class="display-4 mb-5">به رستوران کافه غذا خوش آمدید.</h2>
        <a class="btn btn-lg btn-primary" href="#gallary">منوی رستوران</a>
    </div>
</header>

webs/templates/webs/detail.html
{% extends '_base.html' %}
{% block title %}{{posts.name}}{% endblock title %}
{% block context %}




<div class="card mb-3">
    <img src="{{posts.image.url}}" class="card-img-top" alt="...">
  </div>
<br><br><br><br><br><br><br><br><br>
<div class="container-fluid bg-dark>
  <div class="card mb-3" style="max-width: 100%px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{posts.image.url}}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title" style='color:red;text-align:right;'>{{posts.name}}</h5>
          <p class="card-text" style='color:white;text-align:right;'>{{posts.describtion}}</p>
          <p class="card-text" style='color:white;text-align:right;'>{{posts.price}} تومان</p>
          <p class="card-text" style='color:white;text-align:right;'><small class="text-body-secondary">آخرین آپدیت {{posts.created}}</small></p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock context %}

webs/templates/webs/index.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}

{% block navbar %}
<li class="nav-item">
    <a class="nav-link" href="#about">درباره ما</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="#gallary">منوی رستوران</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'reserve:reserve' %}">رزرو</a>
</li>
</ul>
<a class="navbar-brand m-auto" href="#">
<img src="assets/imgs/logo.svg" class="brand-img" alt="">
<span class="brand-txt">کافه غذا</span>
</a>
<ul class="navbar-nav">
<li class="nav-item">
    <a class="nav-link" href="#blog">بلاگ غذا<span class="sr-only">(current)</span></a>
</li>
<li class="nav-item">
    <a class="nav-link" href="#contact">ارتباط با ما</a>
</li>
{% endblock navbar %}

{% block header %}
{% include 'header.html' %}
{% endblock header %}   

{% block context %}
    <!--  About Section  -->
    <div id="about" class="container-fluid wow fadeIn" id="about"data-wow-duration="1.5s">
        <div class="row">
            <div class="col-lg-6 has-img-bg"></div>
            <div class="col-lg-6">
                <div class="row justify-content-center" style="text-align:right;">
                    <div class="col-sm-8 py-5 my-5">
                        <h2 class="mb-4">درباره ما</h2>
                        <p>هدف اصلی در این مجموعه ایجاد تجربه ای متمایز از غذاهای ایرانی تهیه شده از گوشت گوسفند و کباب های منحصر بفرد ایرانی و ارتقای چایگاه غذاها و سنت های ایرانی در میان علاقمندان در سطح بین المللی است. کافه غذا با مشعوف کردن میهمانان با ارائه بالاترین کیفیت غذاهای ایرانی که مطلوبیت جهانی دارد به مصرف کننده ها ارزش می دهد. این ارزش از همان مراحل اولیه که مواد اولیه است آغاز می گردد. تجربه چند دهه در تهیه مواد اولیه مرغوب و متمایز , ثبات کیفیت و گزینش غذاهایی که مطلوبیت عمومی و جهانی دارد و در آن لذت از طعم گوشت نقش اساسی دارد. کافه غذا در تنوع غذاها هارمونی متناسبی را حفظ کرده و غذاها را شایسته میهمانان ارائه می کند و این رویه را پیوسته حفظ کرده است.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--  gallary Section  -->
    <div id="gallary" class="text-center bg-dark text-light has-height-md middle-items wow fadeIn">
        <h2 class="section-title">منوی رستوران</h2>
    </div>
    <div class="gallary row">
        {% for post in posts %}
        <div class="col-sm-6 col-lg-3 gallary-item wow fadeIn">
            <img src="{{post.image.url}}" alt="" class="gallary-img" height='282.917px' width='282.917px'>
            <a href="{{post.id}}" class="gallary-overlay">
                <i class="gallary-icon ti-plus"></i>
            </a>
        </div>
        {% endfor %}
    </div>
    
    <!-- book a table Section  -->
    {% comment %} <div class="container-fluid has-bg-overlay text-center text-light has-height-lg middle-items" id="book-table">
        <div class="">
            <h2 class="section-title mb-5">BOOK A TABLE</h2>
            <div class="row mb-5">
                <div class="col-sm-6 col-md-3 col-xs-12 my-2">
                    <input type="email" id="booktable" class="form-control form-control-lg custom-form-control" placeholder="EMAIL">
                </div>
                <div class="col-sm-6 col-md-3 col-xs-12 my-2">
                    <input type="number" id="booktable" class="form-control form-control-lg custom-form-control" placeholder="NUMBER OF GUESTS" max="20" min="0">
                </div>
                <div class="col-sm-6 col-md-3 col-xs-12 my-2">
                    <input type="time" id="booktable" class="form-control form-control-lg custom-form-control" placeholder="EMAIL">
                </div>
                <div class="col-sm-6 col-md-3 col-xs-12 my-2">
                    <input type="date" id="booktable" class="form-control form-control-lg custom-form-control" placeholder="12/12/12">
                </div>
            </div>
            <a href="#" class="btn btn-lg btn-primary" id="rounded-btn">FIND TABLE</a>
        </div>
    </div> {% endcomment %}

    <!-- BLOG Section  -->
    <div id="blog" class="container-fluid bg-dark text-light py-5 text-center wow fadeIn">
        {% comment %} <h2 class="section-title py-5">EVENTS AT THE FOOD HUT</h2> {% endcomment %}
        <div class="row justify-content-center">
            <div class="col-sm-7 col-md-4 mb-5">
                <ul class="nav nav-pills nav-justified mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#foods" role="tab" aria-controls="pills-home" aria-selected="true">فست فود</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#irani" role="tab" aria-controls="pills-profile" aria-selected="false">غذاهای ایرانی</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#juices" role="tab" aria-controls="pills-profile" aria-selected="false">نوشیدنی</a>
                    </li>
                </ul>
            </div>
        </div>


        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="foods" role="tabpanel" aria-labelledby="pills-home-tab">
                <div class="row">
                    {% for post in posts %}
                    {% if 'fastfood' in post.type %}
                    <div class="col-md-4">
                        <div class="card bg-transparent border my-3 my-md-0">
                            <img src="{{post.image.url}}" alt="" class="rounded-0 card-img-top mg-responsive" width='185.317px' height='347.767px'>
                            <div class="card-body">
                                <h1 class="text-center mb-4"><a href="{{post.id}}" class="badge badge-primary">{{post.price}} تومان</a></h1>
                                <h4 class="pt20 pb20">{{post.name}}</h4>
                                <p class="text-white">{{post.describtion}}</p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="tab-pane fade" id="irani" role="tabpanel" aria-labelledby="pills-home-tab">
                <div class="row">
                    {% for post in posts %}
                    {% if 'iranifood' in post.type %}
                    <div class="col-md-4">
                        <div class="card bg-transparent border my-3 my-md-0">
                            <img src="{{post.image.url}}" alt="" class="rounded-0 card-img-top mg-responsive" width='185.317px' height='347.767px'>
                            <div class="card-body">
                                <h1 class="text-center mb-4"><a href="{{post.id}}" class="badge badge-primary">{{post.price}} تومان</a></h1>
                                <h4 class="pt20 pb20">{{post.name}}</h4>
                                <p class="text-white">{{post.describtion}}</p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            <div class="tab-pane fade" id="juices" role="tabpanel" aria-labelledby="pills-home-tab">
                <div class="row">
                    {% for post in posts %}
                    {% if 'juices' in post.type %}
                    <div class="col-md-4">
                        <div class="card bg-transparent border my-3 my-md-0">
                            <img src="{{post.image.url}}" alt="" class="rounded-0 card-img-top mg-responsive" width='185.317px' height='347.767px'>
                            <div class="card-body">
                                <h1 class="text-center mb-4"><a href="{{post.id}}" class="badge badge-primary">{{post.price}} تومان</a></h1>
                                <h4 class="pt20 pb20">{{post.name}}</h4>
                                <p class="text-white">{{post.describtion}}</p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <!-- REVIEWS Section  -->
    {% comment %} <div id="testmonial" class="container-fluid wow fadeIn bg-dark text-light has-height-lg middle-items">
        <h2 class="section-title my-5 text-center">REVIEWS</h2>
        <div class="row mt-3 mb-5">
            <div class="col-md-4 my-3 my-md-0">
                <div class="testmonial-card">
                    <h3 class="testmonial-title">John Doe</h3>
                    <h6 class="testmonial-subtitle">Web Designer</h6>
                    <div class="testmonial-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Earum nobis eligendi, quaerat accusamus ipsum sequi dignissimos consequuntur blanditiis natus. Aperiam!</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 my-3 my-md-0">
                <div class="testmonial-card">
                    <h3 class="testmonial-title">Steve Thomas</h3>
                    <h6 class="testmonial-subtitle">UX/UI Designer</h6>
                    <div class="testmonial-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum minus obcaecati cum eligendi perferendis magni dolorum ipsum magnam, sunt reiciendis natus. Aperiam!</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 my-3 my-md-0">
                <div class="testmonial-card">
                    <h3 class="testmonial-title">Miranda Joy</h3>
                    <h6 class="testmonial-subtitle">Graphic Designer</h6>
                    <div class="testmonial-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, nam. Earum nobis eligendi, dignissimos consequuntur blanditiis natus. Aperiam!</p>
                    </div>
                </div>
            </div>
        </div>
    </div> {% endcomment %}

    <!-- CONTACT Section  -->
    <div id="contact" class="container-fluid bg-dark text-light border-top wow fadeIn">
        <div class="row">
            <div class="col-md-6 px-0">
                <div id="map" style="width: 100%; height: 100%; min-height: 400px"></div>
            </div>
            <div class="col-md-6 px-5 has-height-lg middle-items">
                <h3>FIND US</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit, laboriosam doloremque odio delectus, sunt magnam laborum impedit molestiae, magni quae ipsum, ullam eos! Alias suscipit impedit et, adipisci illo quam.</p>
                <div class="text-muted">
                    <p><span class="ti-location-pin pr-3"></span> 12345 Fake ST NoWhere, AB Country</p>
                    <p><span class="ti-support pr-3"></span> (123) 456-7890</p>
                    <p><span class="ti-email pr-3"></span>info@website.com</p>
                </div>
            </div>
        </div>
    </div>
{% endblock context %}